# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

target 'Signature' do
    pod 'MBProgressHUD', :git => "https://github.com/jdg/MBProgressHUD.git"
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'WYPopoverController'
    pod 'PureLayout'
    pod 'FontAwesomeKit'
    pod 'STPopup'
end
